// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcsjqxvieijxjwzfzdll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjc2pxeHZpZWlqeGp3emZ6ZGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NTkxNzcsImV4cCI6MjA4NzMzNTE3N30.2blRCLXdhmlvYVOm6lh_IYi5rrRBLVl1kGGC8_zWi24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});