// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzsflwdtfkcasardtwhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6c2Zsd2R0ZmtjYXNhcmR0d2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzI1ODMsImV4cCI6MjA4NzM0ODU4M30.UPXK73_CLHJLntV3Nrr4gvO0YJssjt-leUbDqiHzsBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});